CREATE TABLE IMPORT_PRICE
(
    WSS_PRICE_ID            NUMBER(17) NOT NULL,  
    LINE_NUMBER             NUMBER(10) NOT NULL,
    IMPORT_TIMESTAMP        TIMESTAMP  NOT NULL,
    RECORD_TYPE             VARCHAR2(5),
    R_SECURITIES_CODE       VARCHAR2(12),
    R_ISIN                  VARCHAR2(24),
   
   ...
   
    LISTING_TYPE            NUMBER(1),    
    CLOSING_PRICE           NUMBER,    
    CONSTRAINT U_WSS_IMPORT_PRICE UNIQUE(WSS_PRICE_ID)
) NOLOGGING;